version: "3.9"
services:
  collateralsservice:
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - cservicenet
  collateralsservicetests:
    build:
      dockerfile: Dockerfile-test
    networks:
      - cservicenet
    depends_on:
      - collateralsservice
    external_links:
      - collateralsservice:collateralsservice
    environment:
      APP_HOST: collateralsservice
networks:
  cservicenet:
      name: cservicenet
      driver: bridge